# Data Prepping World Bank 
This notebook loads the required variables directly from the World Bank Database and merges them to the existing dataset containing UCDP and FORGE data. The following variables are obtained from the World Bank: oil rents, forest coverage, percentage of rural population and Internet usage. The variables have missing values and need to be imputed.

In [1]:
### Load libraries -------
import pandas as pd
import matplotlib.pyplot as plt
from matplotlib import rcParams
import numpy as np
import os
import wbdata  # <--- use World Bank library to load data

# Pandas parameters
#pd.set_option('display.max_colwidth', -1)
#pd.set_option('display.max_rows', 2000)
#pd.set_option('display.max_columns', 500)

In [2]:
### Define plot parameters ------
plt.rcParams["font.family"] = "garamond"
plt.rcParams.update({'font.size': 22})
rcParams.update({'figure.autolayout': True})

In [3]:
### Define out paths ------

# check if out path exists, if it does not exists add the path
if not os.path.exists('C:\\Users\\frank\\Desktop\\master_thesis_out'):
    os.makedirs('C:\\Users\\frank\\Desktop\\master_thesis_out')

# add subfolders for the out path
out_paths = {
    "desciptive_plots_outcome": 'C:\\Users\\frank\\Desktop\\master_thesis_out\desciptive_plots_outcome',
    "desciptive_tables_outcome": 'C:\\Users\\frank\\Desktop\\master_thesis_out\desciptive_tables_outcome',
    "data": 'C:\\Users\\frank\\Desktop\\master_thesis_out\data'
}

for key, val in out_paths.items():
    if not os.path.exists(val):
        os.makedirs(val)
        
out_paths["desciptive_tables_outcome"]

'C:\\Users\\frank\\Desktop\\master_thesis_out\\desciptive_tables_outcome'

In [4]:
### Load data --------
ucdp_forge = pd.read_csv(os.path.join(out_paths["data"], "ucdp_forge.csv"))
ucdp_forge.head(4)
len(ucdp_forge)

2065

In [5]:
### Check country codes to merge with world bank -----------
# World bank data has their own country codes which are slightly different than iso codes
# check country codes directly on the webpage for example https://data.worldbank.org/country/algeria
con_codes = ucdp_forge.groupby(["StateAbb",'cname']).size().reset_index().rename(columns={0:'count'})
con_codes.head(3)

  StateAbb        cname  count
0      AFG  Afghanistan     64
1      ALG      Algeria     41
2      ANG       Angola     60

In [6]:
### Copy existing country codes and then replace codes to match world bank manually --------------------------- 
ucdp_forge["ccode_wb"] = ucdp_forge["StateAbb"]

# A. 
ucdp_forge.loc[ucdp_forge['StateAbb'] == "ALG", 'ccode_wb'] = "DZA"
ucdp_forge.loc[ucdp_forge['StateAbb'] == "ANG", 'ccode_wb'] = "AGO"

# B.
ucdp_forge.loc[ucdp_forge['StateAbb'] == "BNG", 'ccode_wb'] = "BGD"
ucdp_forge.loc[ucdp_forge['StateAbb'] == "BOS", 'ccode_wb'] = "BIH"
ucdp_forge.loc[ucdp_forge['StateAbb'] == "BUI", 'ccode_wb'] = "BDI"

# C.
ucdp_forge.loc[ucdp_forge['StateAbb'] == "CAM", 'ccode_wb'] = "KHM"
ucdp_forge.loc[ucdp_forge['StateAbb'] == "CDI", 'ccode_wb'] = "CIV"
ucdp_forge.loc[ucdp_forge['StateAbb'] == "CEN", 'ccode_wb'] = "CAF"
ucdp_forge.loc[ucdp_forge['StateAbb'] == "CHA", 'ccode_wb'] = "TCD"
ucdp_forge.loc[ucdp_forge['StateAbb'] == "CON", 'ccode_wb'] = "COG"
ucdp_forge.loc[ucdp_forge['StateAbb'] == "CRO", 'ccode_wb'] = "HRV"

# D.
ucdp_forge.loc[ucdp_forge['StateAbb'] == "DRC", 'ccode_wb'] = "COD"

# G. 
ucdp_forge.loc[ucdp_forge['StateAbb'] == "GRG", 'ccode_wb'] = "GEO"
ucdp_forge.loc[ucdp_forge['StateAbb'] == "GUA", 'ccode_wb'] = "GTM"
ucdp_forge.loc[ucdp_forge['StateAbb'] == "GUI", 'ccode_wb'] = "GIN"

# H. 
ucdp_forge.loc[ucdp_forge['StateAbb'] == "HAI", 'ccode_wb'] = "HTI"

# I.
ucdp_forge.loc[ucdp_forge['StateAbb'] == "INS", 'ccode_wb'] = "IDN"

# L.
ucdp_forge.loc[ucdp_forge['StateAbb'] == "LES", 'ccode_wb'] = "LSO"
ucdp_forge.loc[ucdp_forge['StateAbb'] == "LEB", 'ccode_wb'] = "LBN" 
ucdp_forge.loc[ucdp_forge['StateAbb'] == "LIB", 'ccode_wb'] = "LBY"

# M. 
ucdp_forge.loc[ucdp_forge['StateAbb'] == "MAA", 'ccode_wb'] = "MRT"
ucdp_forge.loc[ucdp_forge['StateAbb'] == "MAC", 'ccode_wb'] = "MKD"
ucdp_forge.loc[ucdp_forge['StateAbb'] == "MLD", 'ccode_wb'] = "MDA"
ucdp_forge.loc[ucdp_forge['StateAbb'] == "MOR", 'ccode_wb'] = "MAR"
ucdp_forge.loc[ucdp_forge['StateAbb'] == "MYA", 'ccode_wb'] = "MMR"
ucdp_forge.loc[ucdp_forge['StateAbb'] == "MZM", 'ccode_wb'] = "MOZ"

# N. 
ucdp_forge.loc[ucdp_forge['StateAbb'] == "NEP", 'ccode_wb'] = "NPL"
ucdp_forge.loc[ucdp_forge['StateAbb'] == "NIG", 'ccode_wb'] = "NGA"
ucdp_forge.loc[ucdp_forge['StateAbb'] == "NIR", 'ccode_wb'] = "NER"

# P.
ucdp_forge.loc[ucdp_forge['StateAbb'] == "PAR", 'ccode_wb'] = "PRY"
ucdp_forge.loc[ucdp_forge['StateAbb'] == "PHI", 'ccode_wb'] = "PHL"

# R.
ucdp_forge.loc[ucdp_forge['StateAbb'] == "ROM", 'ccode_wb'] = "ROU"

# S.
ucdp_forge.loc[ucdp_forge['StateAbb'] == "SAL", 'ccode_wb'] = "SLV"
ucdp_forge.loc[ucdp_forge['StateAbb'] == "SIE", 'ccode_wb'] = "SLE"
ucdp_forge.loc[ucdp_forge['StateAbb'] == "SPN", 'ccode_wb'] = "ESP"
ucdp_forge.loc[ucdp_forge['StateAbb'] == "SRI", 'ccode_wb'] = "LKA"
ucdp_forge.loc[ucdp_forge['StateAbb'] == "SUD", 'ccode_wb'] = "SDN"

# T. 
ucdp_forge.loc[ucdp_forge['StateAbb'] == "TAJ", 'ccode_wb'] = "TJK"
ucdp_forge.loc[ucdp_forge['StateAbb'] == "THI", 'ccode_wb'] = "THA"
ucdp_forge.loc[ucdp_forge['StateAbb'] == "TRI", 'ccode_wb'] = "TTO"

# U. 
ucdp_forge.loc[ucdp_forge['StateAbb'] == "UKG", 'ccode_wb'] = "GBR"

# Y. 
ucdp_forge.loc[ucdp_forge['StateAbb'] == "YAR", 'ccode_wb'] = "YEM" 
ucdp_forge.loc[ucdp_forge['StateAbb'] == "YUG", 'ccode_wb'] = "SRB" ### Recode Yugoslavia as Serbia

In [7]:
### Search for indicators in wb data --------------------
wbdata.search_indicators("rents")

id                          name
--------------------------  ------------------------------------------------------------------------------------------------------------------------
IC.ELC.LMTG.OUTG.01.DB1619  Getting electricity: Financial deterrents aimed at limiting outages (0-1) (DB16-20 methodology)
NY.GDP.COAL.RT.ZS           Coal rents (% of GDP)
NY.GDP.FRST.RT.ZS           Forest rents (% of GDP)
NY.GDP.MINR.RT.ZS           Mineral rents (% of GDP)
NY.GDP.NGAS.RT.ZS           Natural gas rents (% of GDP)
NY.GDP.PETR.RT.ZS           Oil rents (% of GDP)
NY.GDP.TOTL.RT.ZS           Total natural resources rents (% of GDP)
SABER.GRVT.GOAL7            SABER: (Engaging the Private Sector, Government funded) Policy Goal 7: Empowering all parents, students, and communities
SABER.PRVT.GOAL3            SABER: (Engaging the Private Sector) Policy Goal 3: Empowering all parents, students, and communities
SG.IHT.ASST.PT.EQ           Sons and daughters have equal rights to inherit assets from their parents (1=yes; 0=no)

In [8]:
### Get data for oil rents  --------
# Source on the Internet: https://data.worldbank.org/indicator/NY.GDP.PETR.RT.ZS
oil = pd.DataFrame.from_dict(wbdata.get_data("NY.GDP.PETR.RT.ZS"))
oil_s = oil[["countryiso3code", "date", "value"]]
oil_s = oil_s.rename(columns={'countryiso3code': 'iso3', 'date': 'year', 'value': 'oil'})
oil_s.head(3)

  iso3  year        oil
0  ARB  2020        NaN
1  ARB  2019  19.194321
2  ARB  2018  21.545380

In [9]:
### Merge oil variable with existing dataset (how = left) ----------
oil_s['year']=oil_s['year'].astype(int)
ucdp_forge_oil = pd.merge(ucdp_forge, oil_s, how='left', left_on=['year', 'ccode_wb'], right_on=['year', 'iso3'])
ucdp_forge_oil.head(4)

,year,StateAbb,ccode,cname,side_a,side_a_new_id,side_b,side_b_new_id,dyad_name,dyad_new_id,...,ident_ethnicity,ident_religious,parent_undefined,parent_splinter_nonstate,parent_splinter_state,parent_civil_society,parent_merger,ccode_wb,iso3,oil
0,1990,IRN,630,Iran,Government of Iran,114,KDPI,164,Government of Iran - KDPI,406,...,1,0,0,0,0,1,0,IRN,IRN,21.474983
1,1991,IRN,630,Iran,Government of Iran,114,KDPI,164,Government of Iran - KDPI,406,...,1,0,0,0,0,1,0,IRN,IRN,NaN
2,1992,IRN,630,Iran,Government of Iran,114,KDPI,164,Government of Iran - KDPI,406,...,1,0,0,0,0,1,0,IRN,IRN,NaN
3,1993,IRN,630,Iran,Government of Iran,114,KDPI,164,Government of Iran - KDPI,406,...,1,0,0,0,0,1,0,IRN,IRN,28.998400

In [10]:
### Check if merge was successful ---------
codes = ucdp_forge_oil.groupby(["ccode_wb", 'iso3']).size()
len(ucdp_forge["StateAbb"].unique())
len(codes)

73

In [11]:
### Delete merge variable ----
ucdp_forge_oil = ucdp_forge_oil.drop(['iso3'], 1)
len(ucdp_forge_oil)

2065

In [12]:
### Search for indicators in wb data --------------------
wbdata.search_indicators("forest area")

id              name
--------------  ----------------------------
AG.LND.FRST.HA  Forest area (hectares)
AG.LND.FRST.K2  Forest area (sq. km)
AG.LND.FRST.ZS  Forest area (% of land area)

In [13]:
### There is an issue with the database, data can only be loaded when specifying the required countries -----
countries = list(ucdp_forge["ccode_wb"].unique())
len(countries)

73

In [14]:
### Get data for forest coverage  --------
# Source on the Internet: https://data.worldbank.org/indicator/AG.LND.FRST.ZS
forest_cov = pd.DataFrame.from_dict(wbdata.get_data("AG.LND.FRST.ZS", country= countries))
forest_cov_s = forest_cov[["countryiso3code", "date", "value"]]
forest_cov_s = forest_cov_s.rename(columns={'countryiso3code': 'iso3', 'date': 'year', 'value': 'forest_cov'})
forest_cov_s.head(3)

  iso3  year  forest_cov
0  AFG  2020         NaN
1  AFG  2019         NaN
2  AFG  2018    1.850994

In [15]:
### Merge forest coverage variable with existing dataset (how = left) -------
forest_cov_s['year']=forest_cov_s['year'].astype(int)
ucdp_forge_oil_forestcov = pd.merge(ucdp_forge_oil, forest_cov_s, how='left', left_on=['year', 'ccode_wb'], right_on=['year', 'iso3'])
ucdp_forge_oil_forestcov.head(4)

,year,StateAbb,ccode,cname,side_a,side_a_new_id,side_b,side_b_new_id,dyad_name,dyad_new_id,...,ident_religious,parent_undefined,parent_splinter_nonstate,parent_splinter_state,parent_civil_society,parent_merger,ccode_wb,oil,iso3,forest_cov
0,1990,IRN,630,Iran,Government of Iran,114,KDPI,164,Government of Iran - KDPI,406,...,0,0,0,0,1,0,IRN,21.474983,IRN,5.572374
1,1991,IRN,630,Iran,Government of Iran,114,KDPI,164,Government of Iran - KDPI,406,...,0,0,0,0,1,0,IRN,NaN,IRN,5.587699
2,1992,IRN,630,Iran,Government of Iran,114,KDPI,164,Government of Iran - KDPI,406,...,0,0,0,0,1,0,IRN,NaN,IRN,5.603023
3,1993,IRN,630,Iran,Government of Iran,114,KDPI,164,Government of Iran - KDPI,406,...,0,0,0,0,1,0,IRN,28.998400,IRN,5.618348

In [16]:
### Check if merge was successful ---------
codes = ucdp_forge_oil_forestcov.groupby(["ccode_wb", 'iso3']).size()
len(ucdp_forge["StateAbb"].unique())
len(codes)

73

In [17]:
### Delete merge variable ----
ucdp_forge_oil_forestcov = ucdp_forge_oil_forestcov.drop(['iso3'], 1)
len(ucdp_forge_oil_forestcov)

2065

In [18]:
### Search for indicators in wb data --------------------
wbdata.search_indicators("rural population")

id                            name
----------------------------  ---------------------------------------------------------------------------------------------------------------
1.2_ACCESS.ELECTRICITY.RURAL  Access to electricity (% of rural population)
EG.ELC.ACCS.RU.ZS             Access to electricity, rural (% of rural population)
EG.NSF.ACCS.RU.ZS             Access to non-solid fuel, rural (% of rural population)
EN.POP.EL5M.RU.ZS             Rural population living in areas where elevation is below 5 meters (% of total population)
EN.RUR.DNST                   Rural population density (rural population per sq. km of arable land)
SH.H2O.BASW.RU.Q1.ZS          People using at least basic drinking water services, rural (% of rural population): Q1 (lowest)
SH.H2O.BASW.RU.Q2.ZS          People using at least basic drinking water services, rural (% of rural population): Q2
SH.H2O.BASW.RU.Q3.ZS          People using at least basic drinking water services, rural (% of rural population): Q3
SH.H2O.BASW.RU.Q4.ZS          People using at least basic drinking water services, rural (% of rural population): Q4
SH.H2O.BASW.RU.Q5.ZS          People using at least basic drinking water services, rural (% of rural population): Q5 (highest)
SH.H2O.BASW.RU.ZS             People using at least basic drinking water services, rural (% of rural population)
SH.H2O.SAFE.RU.ZS             Improved water source, rural (% of rural population with access)
SH.H2O.SMDW.RU.ZS             People using safely managed drinking water services, rural (% of rural population)
SH.STA.ACSN.RU                Improved sanitation facilities, rural (% of rural population with access)
SH.STA.BASS.RU.Q1.ZS          People using at least basic sanitation services, rural (% of rural population): Q1 (lowest)
SH.STA.BASS.RU.Q2.ZS          People using at least basic sanitation services, rural (% of rural population): Q2
SH.STA.BASS.RU.Q3.ZS          People using at least basic sanitation services, rural (% of rural population): Q3
SH.STA.BASS.RU.Q4.ZS          People using at least basic sanitation services, rural (% of rural population): Q4
SH.STA.BASS.RU.Q5.ZS          People using at least basic sanitation services, rural (% of rural population): Q5 (highest)
SH.STA.BASS.RU.ZS             People using at least basic sanitation services, rural (% of rural population)
SH.STA.HYGN.RU.Q1.ZS          People with basic handwashing facilities including soap and water, rural (% of rural population): Q1 (lowest)
SH.STA.HYGN.RU.Q2.ZS          People with basic handwashing facilities including soap and water, rural (% of rural population): Q2
SH.STA.HYGN.RU.Q3.ZS          People with basic handwashing facilities including soap and water, rural (% of rural population): Q3
SH.STA.HYGN.RU.Q4.ZS          People with basic handwashing facilities including soap and water, rural (% of rural population): Q4
SH.STA.HYGN.RU.Q5.ZS          People with basic handwashing facilities including soap and water, rural (% of rural population): Q5 (highest)
SH.STA.HYGN.RU.ZS             People with basic handwashing facilities including soap and water, rural (% of rural population)
SH.STA.ODFC.RU.Q1.ZS          People practicing open defecation, rural (% of rural population): Q1 (lowest)
SH.STA.ODFC.RU.Q2.ZS          People practicing open defecation, rural (% of rural population): Q2
SH.STA.ODFC.RU.Q3.ZS          People practicing open defecation, rural (% of rural population): Q3
SH.STA.ODFC.RU.Q4.ZS          People practicing open defecation, rural (% of rural population): Q4
SH.STA.ODFC.RU.Q5.ZS          People practicing open defecation, rural (% of rural population): Q5 (highest)
SH.STA.ODFC.RU.ZS             People practicing open defecation, rural (% of rural population)
SH.STA.SMSS.RU.ZS             People using safely managed sanitation services, rural (% of rural population)
SI.POV.DDAY.RU                Poverty headcount ratio at $1.90 a day, rural (2011 PPP) (% of rural population)
SI.POV.RUHC                   Rural poverty headcount ratio at national poverty lines (% of rural population)
SI.POV.RUHC.NC                Rural poverty headcount ratio at national poverty lines (% of rural population), including noncomparable values
SP.RUR.TOTL                   Rural population
SP.RUR.TOTL.FE.ZS             Rural population, female (% of total)
SP.RUR.TOTL.MA.ZS             Rural population, male (% of total)
SP.RUR.TOTL.ZG                Rural population growth (annual %)
SP.RUR.TOTL.ZS                Rural population (% of total population)

In [19]:
### Get data for rural population  --------
rural = pd.DataFrame.from_dict(wbdata.get_data("SP.RUR.TOTL.ZS"))
rural_s = rural[["countryiso3code", "date", "value"]]
rural_s = rural_s.rename(columns={'countryiso3code': 'iso3', 'date': 'year', 'value': 'rural'})
rural_s.head(3)

  iso3  year      rural
0  ARB  2020        NaN
1  ARB  2019  40.798353
2  ARB  2018  41.074581

In [20]:
### Merge rural population variable with existing dataset (how = left) -----
# Source on the Internet: https://data.worldbank.org/indicator/SP.RUR.TOTL.ZS
rural_s['year']=rural_s['year'].astype(int)
ucdp_forge_oil_forestcov_rural = pd.merge(ucdp_forge_oil_forestcov, rural_s, how='left', left_on=['year', 'ccode_wb'], right_on=['year', 'iso3'])
ucdp_forge_oil_forestcov_rural.head(4)

,year,StateAbb,ccode,cname,side_a,side_a_new_id,side_b,side_b_new_id,dyad_name,dyad_new_id,...,parent_undefined,parent_splinter_nonstate,parent_splinter_state,parent_civil_society,parent_merger,ccode_wb,oil,forest_cov,iso3,rural
0,1990,IRN,630,Iran,Government of Iran,114,KDPI,164,Government of Iran - KDPI,406,...,0,0,0,1,0,IRN,21.474983,5.572374,IRN,43.670
1,1991,IRN,630,Iran,Government of Iran,114,KDPI,164,Government of Iran - KDPI,406,...,0,0,0,1,0,IRN,NaN,5.587699,IRN,43.135
2,1992,IRN,630,Iran,Government of Iran,114,KDPI,164,Government of Iran - KDPI,406,...,0,0,0,1,0,IRN,NaN,5.603023,IRN,42.347
3,1993,IRN,630,Iran,Government of Iran,114,KDPI,164,Government of Iran - KDPI,406,...,0,0,0,1,0,IRN,28.998400,5.618348,IRN,41.481

In [21]:
### Check if merge was successful ---------
codes = ucdp_forge_oil_forestcov_rural.groupby(["ccode_wb", 'iso3']).size()
len(ucdp_forge["StateAbb"].unique())
len(codes)

73

In [22]:
### Delete merge variable ----
ucdp_forge_oil_forestcov_rural = ucdp_forge_oil_forestcov_rural.drop(['iso3'], 1)
len(ucdp_forge_oil_forestcov_rural)

2065

In [23]:
### Search for indicators in wb data --------------------
wbdata.search_indicators("internet")

id                                    name
------------------------------------  ------------------------------------------------------------------------------------------------------------------------------------------------
2.0.cov.Int                           Coverage: Internet
2.0.hoi.Int                           HOI: Internet
fin14a.a                              Used the internet to pay bills in the past year (% age 15+)
fin14a.a.1                            Used the internet to pay bills in the past year, male (% age 15+)
fin14a.a.10                           Used the internet to pay bills in the past year, in labor force  (% age 15+)
fin14a.a.11                           Used the internet to pay bills in the past year, out of labor force (% age 15+)
fin14a.a.2                            Used the internet to pay bills in the past year , female(% age 15+)
fin14a.a.3                            Used the internet to pay bills in the past year , young adults (% age 15-24)
fin14a.a.4                            Used the internet to pay bills in the past year , older adults (% age 25+)
fin14a.a.5                            Used the internet to pay bills in the past year, primary education or less (% age 15+)
fin14a.a.6                            Used the internet to pay bills in the past year , secondary education or more (% age 15+)
fin14a.a.7                            Used the internet to pay bills in the past year, income, poorest 40%(% age 15+)
fin14a.a.8                            Used the internet to pay bills in the past year , income, richest 60%(% age 15+)
fin14a.a.9                            Used the internet to pay bills in the past year , rural (% age 15+)
fin14abca.t.d                         Used the internet to pay bills or to buy something online in the past year (% age 15+)
fin14abca.t.d.1                       Used the internet to pay bills or to buy something online in the past year, male (% age 15+)
fin14abca.t.d.10                      Used the internet to pay bills or to buy something online in the past year, in labor force (% age 15+)
fin14abca.t.d.11                      Used the internet to pay bills or to buy something online in the past year, out of labor force (% age 15+)
fin14abca.t.d.2                       Used the internet to pay bills or to buy something online in the past year, female (% age 15+)
fin14abca.t.d.3                       Used the internet to pay bills or to buy something online in the past year, young adults (% age 15-24)
fin14abca.t.d.4                       Used the internet to pay bills or to buy something online in the past year, older adults (% age 25+)
fin14abca.t.d.5                       Used the internet to pay bills or to buy something online in the past year, primary education or less (% age 15+)
fin14abca.t.d.6                       Used the internet to pay bills or to buy something online in the past year, secondary education or less (% age 15+)
fin14abca.t.d.7                       Used the internet to pay bills or to buy something online in the past year, income, poorest 40% (% age 15+)
fin14abca.t.d.8                       Used the internet to pay bills or to buy something online in the past year, income, richest 60% (% age 15+)
fin14abca.t.d.9                       Used the internet to pay bills or to buy something online in the past year, rural (% age 15+)
fin14b.a                              Used the internet to buy something online in the past year(% age 15+)
fin14b.a.1                            Used the internet to buy something online in the past year, male(% age 15+)
fin14b.a.10                           Used the internet to buy something online in the past year, in labor force (% age 15+)
fin14b.a.11                           Used the internet to buy something online in the past year, out of labor force (% age 15+)
fin14b.a.2                            Used the internet to buy something online in the past year, female(% age 15+)
fin14b.a.3                            Used the internet to buy something online in the past year, young adults (% age 15-24)
fin14b.a.4                            Used the internet to buy something online in the past year, older adults (% age 25+)
fin14b.a.5                            Used the internet to buy something online in the past year, primary education or less (% age 15+)
fin14b.a.6                            Used the internet to buy something online in the past year, secondary education or more (% age 15+)
fin14b.a.7                            Used the internet to buy something online in the past year, income, poorest 40% (% age 15+)
fin14b.a.8                            Used the internet to buy something online in the past year, income, richest 60% (% age 15+)
fin14b.a.9                            Used the internet to buy something online in the past year, rural (% age 15+)
fin14ca.a.s                           Paid online for internet purchase (% internet purchasers, age 15+)
fin14cb.a.s                           Paid cash on delivery for internet purchase (% internet purchasers, age 15+)
fin5.a                                Used a mobile phone or the internet to access a financial institution account in the past year (% age 15+)
fin5.a.s                              Used a mobile phone or the internet to access a financial institution account in the past year (% with a financial institution account, age 15+)
fin5.d                                Used a mobile phone or the internet to access an account (% age 15+)
fin5.d.1                              Used a mobile phone or the internet to access an account, male (% age 15+)
fin5.d.10                             Used a mobile phone or the internet to access an account, in labor force  (% age 15+)
fin5.d.11                             Used a mobile phone or the internet to access an account, out of labor force  (% age 15+)
fin5.d.2                              Used a mobile phone or the internet to access an account, female  (% age 15+)
fin5.d.3                              Used a mobile phone or the internet to access an account, young adults (% age 15-24)
fin5.d.4                              Used a mobile phone or the internet to access an account, older adults (% age 25+)
fin5.d.5                              Used a mobile phone or the internet to access an account, primary education or less  (% age 15+)
fin5.d.6                              Used a mobile phone or the internet to access an account, secondary education or more  (% age 15+)
fin5.d.7                              Used a mobile phone or the internet to access an account, income, poorest 40%  (% age 15+)
fin5.d.8                              Used a mobile phone or the internet to access an account, income, richest 60% (% age 15+)
fin5.d.9                              Used a mobile phone or the internet to access an account, rural  (% age 15+)
fin5.d.s                              Used a mobile phone or the internet to access an account (% with an account, age 15+)
fin6.a                                Used a mobile phone or the internet to check account balance in the past year (% age 15+)
fin6_a                                Used a mobile phone or the internet to check account balance in the past year (% age 15+)
fin6_a_1                              Used a mobile phone or the internet to check account balance in the past year, female  (% age 15+)
fin6_a_2                              Used a mobile phone or the internet to check account balance in the past year, male (% age 15+)"
fin6_a_3                              Used a mobile phone or the internet to check account balance in the past year, income, poorest 40% (% age 15+)
fin6_a_4                              Used a mobile phone or the internet to check account balance in the past year, income, richest 60% (% age 15+)
fin6_a_5                              Used a mobile phone or the internet to check account balance in the past year (% ages 15-34)
fin6_a_6                              Used a mobile phone or the internet to check account balance in the past year (% ages 35-59)
fin6_a_7                              Used a mobile phone or the internet to check account balance in the past year (% age 60+)
gf4_n                                 Made payment using a mobile phone or the internet (% age 15+)
gf4_n_1                               Made payment using a mobile phone or the internet, female (% age 15+)
gf4_n_2                               Made payment using a mobile phone or the internet, male (% age 15+)
gf4_n_3                               Made payment using a mobile phone or the internet, income, poorest 40% (% age 15+)
gf4_n_4                               Made payment using a mobile phone or the internet, income, richest 60% (% age 15+)
gf4_n_5                               Made payment using a mobile phone or the internet (% ages 15-34)
gf4_n_6                               Made payment using a mobile phone or the internet (% ages 35-59)
gf4_n_7                               Made payment using a mobile phone or the internet (% age 60+)
gwp2_n                                Access to internet (% age 15+)
gwp2_n_1                              Access to internet, female (% age 15+)
gwp2_n_2                              Access to internet, male (% age 15+)
gwp2_n_3                              Access to internet, income, poorest 40% (% age 15+)
gwp2_n_4                              Access to internet, income, richest 60% (% age 15+)
gwp2_n_5                              Access to internet (% ages 15-34)
gwp2_n_6                              Access to internet (% ages 35-59)
gwp2_n_7                              Access to internet (% age 60+)
IN.POV.HH.ASSETS.COMP.INTERNET.PCT    Households having computer laptops (w/Internet, %)
IN.POV.HH.ASSETS.COMP.NOINTERNET.PCT  Households having computer laptops (w/o Internet, %)
IT.BBD.USEC.CD                        Fixed broadband Internet access tariff (US$ per month)
IT.NET.BNDW                           International Internet bandwidth (Mbps)
IT.NET.BNDW.PC                        International Internet bandwidth (bits per person)
IT.NET.CONN.CD                        Fixed broadband Internet connection charge (current US$)
IT.NET.CONN.CN                        Fixed broadband Internet connection charge (current LCU)
IT.NET.EDUC.ZS                        Schools connected to the Internet (%)
IT.NET.HOST.P4                        Internet hosts (per 10,000 people)
IT.NET.ISPC.CD                        Internet service provider access charges ($ per 30 off-peak hours)
IT.NET.SECR                           Secure Internet servers
IT.NET.SECR.P6                        Secure Internet servers (per 1 million people)
IT.NET.SUB.CD                         Fixed broadband Internet monthly subscription (current US$)
IT.NET.SUB.CN                         Fixed broadband Internet monthly subscription (current LCU)
IT.NET.TELC.CD                        Internet telephone access charges ($ per 30 off-peak hours)
IT.NET.USEC.CD                        Price basket for Internet (US$ per month)
IT.NET.USEC.ZS                        Internet total monthly price (% of monthly GNI per capita)
IT.NET.USER                           Internet users
IT.NET.USER.P2                        Internet users (per 100 people)
IT.NET.USER.P3                        Internet users (per 1,000 people)
IT.NET.USER.ZS                        Individuals using the Internet (% of population)
SF.CMN.INET.USER.10K                  Internet users (per 10,000 people)
UIS.SCHBSP.1.WINTERN                  Proportion of primary schools with access to Internet for pedagogical purposes (%)
UIS.SCHBSP.2.WINTERN                  Proportion of lower secondary schools with access to Internet for pedagogical purposes (%)
UIS.SCHBSP.2T3.WINTERN                Proportion of secondary schools with access to Internet for pedagogical purposes (%)
UIS.SCHBSP.3.WINTERN                  Proportion of upper secondary schools with access to Internet for pedagogical purposes (%)

In [24]:
### Get data for internet usage  --------
# Source on the Internet: https://data.worldbank.org/indicator/IT.NET.USER.ZS
internet_use = pd.DataFrame.from_dict(wbdata.get_data("IT.NET.USER.ZS"))
internet_use_s = internet_use[["countryiso3code", "date", "value"]]
internet_use_s = internet_use_s.rename(columns={'countryiso3code': 'iso3', 'date': 'year', 'value': 'internet_use'})
internet_use_s.head(3)

  iso3  year  internet_use
0  ARB  2020           NaN
1  ARB  2019           NaN
2  ARB  2018     63.166728

In [25]:
### Merge internet usage variable with existing dataset (how = left) -------
internet_use_s['year']=internet_use_s['year'].astype(int)
ucdp_forge_oil_forestcov_rural_internetuse = pd.merge(ucdp_forge_oil_forestcov_rural, 
                                            internet_use_s, how='left', left_on=['year', 'ccode_wb'], right_on=['year', 'iso3'])
ucdp_forge_oil_forestcov_rural_internetuse.head(4)

,year,StateAbb,ccode,cname,side_a,side_a_new_id,side_b,side_b_new_id,dyad_name,dyad_new_id,...,parent_splinter_nonstate,parent_splinter_state,parent_civil_society,parent_merger,ccode_wb,oil,forest_cov,rural,iso3,internet_use
0,1990,IRN,630,Iran,Government of Iran,114,KDPI,164,Government of Iran - KDPI,406,...,0,0,1,0,IRN,21.474983,5.572374,43.670,IRN,0.0
1,1991,IRN,630,Iran,Government of Iran,114,KDPI,164,Government of Iran - KDPI,406,...,0,0,1,0,IRN,NaN,5.587699,43.135,IRN,0.0
2,1992,IRN,630,Iran,Government of Iran,114,KDPI,164,Government of Iran - KDPI,406,...,0,0,1,0,IRN,NaN,5.603023,42.347,IRN,0.0
3,1993,IRN,630,Iran,Government of Iran,114,KDPI,164,Government of Iran - KDPI,406,...,0,0,1,0,IRN,28.998400,5.618348,41.481,IRN,0.0

In [26]:
### Check if merge was successful ---------
codes = ucdp_forge_oil_forestcov_rural_internetuse.groupby(["ccode_wb", 'iso3']).size()
len(ucdp_forge["StateAbb"].unique())
len(codes)

73

In [27]:
### Delete merge variable ----
ucdp_forge_oil_forestcov_rural_internetuse = ucdp_forge_oil_forestcov_rural_internetuse.drop(['iso3'], 1)
len(ucdp_forge_oil_forestcov_rural_internetuse)

2065

In [28]:
### Check missing values in added variables ----
missing = ucdp_forge_oil_forestcov_rural_internetuse[['year',
 'StateAbb', 'forest_cov', 'rural', 'oil', 'internet_use']]
null_data = missing[missing.isnull().any(axis=1)]
null_data.sort_values(by=["StateAbb", "year"]).head(3) # rural has no missing values

     year StateAbb  forest_cov   rural  oil  internet_use
762  1989      AFG         NaN  78.912  NaN           NaN
767  1989      AFG         NaN  78.912  NaN           NaN
781  1989      AFG         NaN  78.912  NaN           NaN

In [29]:
### Which variables are in dataset -------------
dat_var = []
for col in ucdp_forge_oil_forestcov_rural_internetuse.columns:
    dat_var.append(col)
dat_var

['year',
 'StateAbb',
 'ccode',
 'cname',
 'side_a',
 'side_a_new_id',
 'side_b',
 'side_b_new_id',
 'dyad_name',
 'dyad_new_id',
 'active_year',
 'best',
 'high',
 'low',
 'foundloc',
 'foundyear',
 'foundmo',
 'foundday',
 'fightyear',
 'fightmo',
 'fightday',
 'goalnominal',
 'goalindep',
 'goalauto',
 'goalrights',
 'goalrep',
 'goalchange',
 'goaldem',
 'goalother',
 'goalnote',
 'ideology',
 'ideolcom',
 'ideolleft',
 'ideolright',
 'ideolnat',
 'ideolanti',
 'ideolrel',
 'ideoloth',
 'ideolnote',
 'religious',
 'religion',
 'ethnic',
 'ethnicity',
 'preorg',
 'preorgno',
 'preorgreb',
 'preorgter',
 'preorgpar',
 'preorgmvt',
 'preorgyou',
 'preorglab',
 'preorgmil',
 'preorggov',
 'preorgfmr',
 'preorgrel',
 'preorgfor',
 'preorgref',
 'preorgeth',
 'preorgoth',
 'preorgname',
 'merger',
 'splinter',
 'splinterUCDP',
 'foundloc_cat',
 'foundloc_cat_lab',
 'foundloc_cat_cat',
 'foundloc_cat_cat_lab',
 'age_formation',
 'age_active',
 'goal_territory',
 'goal_gov_represent',
 'goal_gov_replace',
 'ideo_left',
 'ideo_right',
 'goal_total',
 'ideo_total',
 'ideo_anti_system',
 'ideo_religious',
 'ident_ethnicity',
 'ident_religious',
 'parent_undefined',
 'parent_splinter_nonstate',
 'parent_splinter_state',
 'parent_civil_society',
 'parent_merger',
 'ccode_wb',
 'oil',
 'forest_cov',
 'rural',
 'internet_use']

In [30]:
### Reset index -----------
ucdp_forge_oil_forestcov_rural_internetuse.reset_index(drop=False, inplace=False)
ucdp_forge_oil_forestcov_rural_internetuse.head(3)

,year,StateAbb,ccode,cname,side_a,side_a_new_id,side_b,side_b_new_id,dyad_name,dyad_new_id,...,parent_undefined,parent_splinter_nonstate,parent_splinter_state,parent_civil_society,parent_merger,ccode_wb,oil,forest_cov,rural,internet_use
0,1990,IRN,630,Iran,Government of Iran,114,KDPI,164,Government of Iran - KDPI,406,...,0,0,0,1,0,IRN,21.474983,5.572374,43.670,0.0
1,1991,IRN,630,Iran,Government of Iran,114,KDPI,164,Government of Iran - KDPI,406,...,0,0,0,1,0,IRN,NaN,5.587699,43.135,0.0
2,1992,IRN,630,Iran,Government of Iran,114,KDPI,164,Government of Iran - KDPI,406,...,0,0,0,1,0,IRN,NaN,5.603023,42.347,0.0

In [31]:
## Save dataset -----------
print(len(ucdp_forge_oil_forestcov_rural_internetuse))
ucdp_forge_oil_forestcov_rural_internetuse.to_csv(os.path.join(out_paths["data"], "ucdp_forge_wb.csv"), index=False, sep=',')

2065